image: adoptopenjdk/maven-openjdk11:latest

variables:
    MAVEN_OPTS: 'Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'

cache:
    paths:
        - .m2/repository

stages:
    - build
    - test
    - delivery

build:
    stage: build
    script:
        - mvn -Dmaven.test.skip=true package
    artifacts:
        paths:
            - target/backend-latest.jar
        
test:
    stage: test
    script:
        - mvn test
        - mvn sonar:sonar

delivery:
    image: docker:latest
    stage: delivery
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build --pull -t $CI_REGISTRY/mvc-entertainment/communify-backend/image:latest .
        - docker push $CI_REGISTRY/mvc-entertainment/communify-backend/image:latest
    only:
        - master