image: adoptopenjdk/maven-openjdk11:latest

stages:
    - build
    - test
    - deploy
    

build:
    stage: build
    script:
        - mvn compile
    artifacts:
        paths:
            - target/
        
test:
    stage: test
    script:
        - mvn test
        - mvn sonar:sonar
    artifacts:
        paths:
            - target/


production:
    stage: deploy
    script:
        - mvn -Dmaven.test.skip=true package
        - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
        - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
        - ./cf push
    only:
        - master