image: adoptopenjdk/maven-openjdk11:latest

before_script:
    - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"

variables:
    REPOSITORY_URL: 380326703863.dkr.ecr.us-east-2.amazonaws.com/gitlabci

stages:
    - build
    - test
    - package
    - deploy
    

build:
    stage: build
    script:
        - mvn compile
        - mvn -Dmaven.test.skip=true package
    artifacts:
        paths:
            - target/
        
test:
    stage: test
    script:
        - mvn test
        - mvn sonar:sonar
    artifacts:
        paths:
            - target/


build-image:
    image: docker:latest
    stage: package
    services:
        - name: docker:dind
    script:
        - apk add --no-cache curl jq python py-pip
        - pip install awscli
        - $(aws ecr get-login --no-include-email --region us-east-2)
        - docker build -t $REPOSITORY_URL:latest .
        - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG
        - docker push $REPOSITORY_URL:latest
        - docker push $REPOSITORY_URL:$IMAGE_TAG

deploy:
    image: python:latest
    stage: deploy
    script:
        - pip install awscli
        - echo $REPOSITORY_URL:$IMAGE_TAG
        - aws ecs register-task-definition --region us-east-2 --family MyTaskDef --cli-input-json file://aws/ecs-task-definition.json
        - aws ecs update-service --region us-east-2 --cluster MyCluster --service MyService  --task-definition MyTaskDef
    only:
        - master