image: adoptopenjdk/maven-openjdk11:latest

stages:
    - build
    - test
    - deploy
    
build:
    stage: build
    script:
        - mvn compile
        
test:
    stage: test
    script:
        - mvn $MAVEN_CLI_OPTS test
        - mvn $MAVEN_CLI_OPTS sonar:sonar
        
deploy:
    stage: deploy
    rules:
        - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
        - if: $CI_COMMIT_BRANCH == 'master'
    script:
        echo "Deploying..."