image: adoptopenjdk/maven-openjdk11:latest


stages:
    - build
    - test
    - delivery

build:
    stage: build
    script:
        - mvn compile
        - mvn -Dmaven.test.skip=true package
    artifacts:
        paths:
            - target/
        
test:
    stage: test
    script:
        - mvn test
        - mvn sonar:sonar
    artifacts:
        paths:
            - target/

delivery:
    image: docker:latest
    stage: delivery
    services:
        - docker:dind
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
    only:
        - master